import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Login from "./auth/Login";
import SignIn from "./auth/Sign In";
import RoomChat from "@/components/RoomChat";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        < RoomChat/>
        {children}
      </body>
    </html>
  );
}
