import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BaseToaster from "@/components/system/BaseToaster";
import { AuthProvider } from "@/context/AuthContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

export const metadata = {
  title: "Ruang Jiwa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-dark ${poppins.className}`}>
        <AuthProvider>
          {/* <Navbar /> */}
          <BaseToaster />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
